{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "38d89d5a-4e45-4a20-9fa2-e0f99898cfb3",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "import streamlit as st"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "cdd321b8-767b-4864-8cb3-4c043206c8fd",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>season</th>\n",
       "      <th>lg</th>\n",
       "      <th>player</th>\n",
       "      <th>player_id</th>\n",
       "      <th>age</th>\n",
       "      <th>team</th>\n",
       "      <th>pos</th>\n",
       "      <th>g</th>\n",
       "      <th>gs</th>\n",
       "      <th>mp_per_game</th>\n",
       "      <th>fg_per_game</th>\n",
       "      <th>fga_per_game</th>\n",
       "      <th>fg_percent</th>\n",
       "      <th>x3p_per_game</th>\n",
       "      <th>x3pa_per_game</th>\n",
       "      <th>x3p_percent</th>\n",
       "      <th>x2p_per_game</th>\n",
       "      <th>x2pa_per_game</th>\n",
       "      <th>x2p_percent</th>\n",
       "      <th>e_fg_percent</th>\n",
       "      <th>ft_per_game</th>\n",
       "      <th>fta_per_game</th>\n",
       "      <th>ft_percent</th>\n",
       "      <th>orb_per_game</th>\n",
       "      <th>drb_per_game</th>\n",
       "      <th>trb_per_game</th>\n",
       "      <th>ast_per_game</th>\n",
       "      <th>stl_per_game</th>\n",
       "      <th>blk_per_game</th>\n",
       "      <th>tov_per_game</th>\n",
       "      <th>pf_per_game</th>\n",
       "      <th>pts_per_game</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2025</td>\n",
       "      <td>NBA</td>\n",
       "      <td>Precious Achiuwa</td>\n",
       "      <td>achiupr01</td>\n",
       "      <td>25.0</td>\n",
       "      <td>NYK</td>\n",
       "      <td>C</td>\n",
       "      <td>57</td>\n",
       "      <td>10.0</td>\n",
       "      <td>20.5</td>\n",
       "      <td>2.9</td>\n",
       "      <td>5.7</td>\n",
       "      <td>0.502</td>\n",
       "      <td>0.2</td>\n",
       "      <td>0.6</td>\n",
       "      <td>0.278</td>\n",
       "      <td>2.7</td>\n",
       "      <td>5.1</td>\n",
       "      <td>0.529</td>\n",
       "      <td>0.517</td>\n",
       "      <td>0.7</td>\n",
       "      <td>1.2</td>\n",
       "      <td>0.594</td>\n",
       "      <td>1.8</td>\n",
       "      <td>3.8</td>\n",
       "      <td>5.6</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.8</td>\n",
       "      <td>0.7</td>\n",
       "      <td>0.8</td>\n",
       "      <td>1.4</td>\n",
       "      <td>6.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2025</td>\n",
       "      <td>NBA</td>\n",
       "      <td>Steven Adams</td>\n",
       "      <td>adamsst01</td>\n",
       "      <td>31.0</td>\n",
       "      <td>HOU</td>\n",
       "      <td>C</td>\n",
       "      <td>58</td>\n",
       "      <td>3.0</td>\n",
       "      <td>13.7</td>\n",
       "      <td>1.6</td>\n",
       "      <td>2.9</td>\n",
       "      <td>0.545</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.000</td>\n",
       "      <td>1.6</td>\n",
       "      <td>2.8</td>\n",
       "      <td>0.552</td>\n",
       "      <td>0.545</td>\n",
       "      <td>0.7</td>\n",
       "      <td>1.6</td>\n",
       "      <td>0.462</td>\n",
       "      <td>2.9</td>\n",
       "      <td>2.8</td>\n",
       "      <td>5.6</td>\n",
       "      <td>1.1</td>\n",
       "      <td>0.4</td>\n",
       "      <td>0.5</td>\n",
       "      <td>0.9</td>\n",
       "      <td>1.0</td>\n",
       "      <td>3.9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2025</td>\n",
       "      <td>NBA</td>\n",
       "      <td>Bam Adebayo</td>\n",
       "      <td>adebaba01</td>\n",
       "      <td>27.0</td>\n",
       "      <td>MIA</td>\n",
       "      <td>C</td>\n",
       "      <td>78</td>\n",
       "      <td>78.0</td>\n",
       "      <td>34.3</td>\n",
       "      <td>6.9</td>\n",
       "      <td>14.3</td>\n",
       "      <td>0.485</td>\n",
       "      <td>1.0</td>\n",
       "      <td>2.8</td>\n",
       "      <td>0.357</td>\n",
       "      <td>5.9</td>\n",
       "      <td>11.4</td>\n",
       "      <td>0.517</td>\n",
       "      <td>0.521</td>\n",
       "      <td>3.2</td>\n",
       "      <td>4.2</td>\n",
       "      <td>0.765</td>\n",
       "      <td>2.4</td>\n",
       "      <td>7.2</td>\n",
       "      <td>9.6</td>\n",
       "      <td>4.3</td>\n",
       "      <td>1.3</td>\n",
       "      <td>0.7</td>\n",
       "      <td>2.1</td>\n",
       "      <td>2.1</td>\n",
       "      <td>18.1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2025</td>\n",
       "      <td>NBA</td>\n",
       "      <td>Ochai Agbaji</td>\n",
       "      <td>agbajoc01</td>\n",
       "      <td>24.0</td>\n",
       "      <td>TOR</td>\n",
       "      <td>SG</td>\n",
       "      <td>64</td>\n",
       "      <td>45.0</td>\n",
       "      <td>27.2</td>\n",
       "      <td>4.2</td>\n",
       "      <td>8.3</td>\n",
       "      <td>0.498</td>\n",
       "      <td>1.6</td>\n",
       "      <td>4.0</td>\n",
       "      <td>0.399</td>\n",
       "      <td>2.6</td>\n",
       "      <td>4.4</td>\n",
       "      <td>0.587</td>\n",
       "      <td>0.593</td>\n",
       "      <td>0.5</td>\n",
       "      <td>0.8</td>\n",
       "      <td>0.708</td>\n",
       "      <td>1.0</td>\n",
       "      <td>2.8</td>\n",
       "      <td>3.8</td>\n",
       "      <td>1.5</td>\n",
       "      <td>0.9</td>\n",
       "      <td>0.5</td>\n",
       "      <td>0.8</td>\n",
       "      <td>2.0</td>\n",
       "      <td>10.4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2025</td>\n",
       "      <td>NBA</td>\n",
       "      <td>Santi Aldama</td>\n",
       "      <td>aldamsa01</td>\n",
       "      <td>24.0</td>\n",
       "      <td>MEM</td>\n",
       "      <td>PF</td>\n",
       "      <td>65</td>\n",
       "      <td>16.0</td>\n",
       "      <td>25.5</td>\n",
       "      <td>4.8</td>\n",
       "      <td>10.0</td>\n",
       "      <td>0.483</td>\n",
       "      <td>1.8</td>\n",
       "      <td>5.0</td>\n",
       "      <td>0.368</td>\n",
       "      <td>3.0</td>\n",
       "      <td>5.0</td>\n",
       "      <td>0.599</td>\n",
       "      <td>0.576</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.4</td>\n",
       "      <td>0.691</td>\n",
       "      <td>1.4</td>\n",
       "      <td>5.0</td>\n",
       "      <td>6.4</td>\n",
       "      <td>2.9</td>\n",
       "      <td>0.8</td>\n",
       "      <td>0.4</td>\n",
       "      <td>1.1</td>\n",
       "      <td>1.2</td>\n",
       "      <td>12.5</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   season   lg            player  player_id   age team pos   g    gs  \\\n",
       "0    2025  NBA  Precious Achiuwa  achiupr01  25.0  NYK   C  57  10.0   \n",
       "1    2025  NBA      Steven Adams  adamsst01  31.0  HOU   C  58   3.0   \n",
       "2    2025  NBA       Bam Adebayo  adebaba01  27.0  MIA   C  78  78.0   \n",
       "3    2025  NBA      Ochai Agbaji  agbajoc01  24.0  TOR  SG  64  45.0   \n",
       "4    2025  NBA      Santi Aldama  aldamsa01  24.0  MEM  PF  65  16.0   \n",
       "\n",
       "   mp_per_game  fg_per_game  fga_per_game  fg_percent  x3p_per_game  \\\n",
       "0         20.5          2.9           5.7       0.502           0.2   \n",
       "1         13.7          1.6           2.9       0.545           0.0   \n",
       "2         34.3          6.9          14.3       0.485           1.0   \n",
       "3         27.2          4.2           8.3       0.498           1.6   \n",
       "4         25.5          4.8          10.0       0.483           1.8   \n",
       "\n",
       "   x3pa_per_game  x3p_percent  x2p_per_game  x2pa_per_game  x2p_percent  \\\n",
       "0            0.6        0.278           2.7            5.1        0.529   \n",
       "1            0.0        0.000           1.6            2.8        0.552   \n",
       "2            2.8        0.357           5.9           11.4        0.517   \n",
       "3            4.0        0.399           2.6            4.4        0.587   \n",
       "4            5.0        0.368           3.0            5.0        0.599   \n",
       "\n",
       "   e_fg_percent  ft_per_game  fta_per_game  ft_percent  orb_per_game  \\\n",
       "0         0.517          0.7           1.2       0.594           1.8   \n",
       "1         0.545          0.7           1.6       0.462           2.9   \n",
       "2         0.521          3.2           4.2       0.765           2.4   \n",
       "3         0.593          0.5           0.8       0.708           1.0   \n",
       "4         0.576          1.0           1.4       0.691           1.4   \n",
       "\n",
       "   drb_per_game  trb_per_game  ast_per_game  stl_per_game  blk_per_game  \\\n",
       "0           3.8           5.6           1.0           0.8           0.7   \n",
       "1           2.8           5.6           1.1           0.4           0.5   \n",
       "2           7.2           9.6           4.3           1.3           0.7   \n",
       "3           2.8           3.8           1.5           0.9           0.5   \n",
       "4           5.0           6.4           2.9           0.8           0.4   \n",
       "\n",
       "   tov_per_game  pf_per_game  pts_per_game  \n",
       "0           0.8          1.4           6.6  \n",
       "1           0.9          1.0           3.9  \n",
       "2           2.1          2.1          18.1  \n",
       "3           0.8          2.0          10.4  \n",
       "4           1.1          1.2          12.5  "
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "per_game = pd.read_csv('/Users/jackewings/Desktop/Practice/Data/NBA_Stats_2025/Player Per Game.csv')\n",
    "\n",
    "pd.set_option('display.max_columns', None)\n",
    "\n",
    "per_game.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "a5654616-2728-4626-93eb-c6d1b613b2c8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Index: 735 entries, 0 to 734\n",
      "Data columns (total 32 columns):\n",
      " #   Column         Non-Null Count  Dtype  \n",
      "---  ------         --------------  -----  \n",
      " 0   season         735 non-null    int64  \n",
      " 1   lg             735 non-null    object \n",
      " 2   player         735 non-null    object \n",
      " 3   player_id      735 non-null    object \n",
      " 4   age            735 non-null    float64\n",
      " 5   team           735 non-null    object \n",
      " 6   pos            735 non-null    object \n",
      " 7   g              735 non-null    int64  \n",
      " 8   gs             735 non-null    float64\n",
      " 9   mp_per_game    735 non-null    float64\n",
      " 10  fg_per_game    735 non-null    float64\n",
      " 11  fga_per_game   735 non-null    float64\n",
      " 12  fg_percent     731 non-null    float64\n",
      " 13  x3p_per_game   735 non-null    float64\n",
      " 14  x3pa_per_game  735 non-null    float64\n",
      " 15  x3p_percent    690 non-null    float64\n",
      " 16  x2p_per_game   735 non-null    float64\n",
      " 17  x2pa_per_game  735 non-null    float64\n",
      " 18  x2p_percent    724 non-null    float64\n",
      " 19  e_fg_percent   731 non-null    float64\n",
      " 20  ft_per_game    735 non-null    float64\n",
      " 21  fta_per_game   735 non-null    float64\n",
      " 22  ft_percent     693 non-null    float64\n",
      " 23  orb_per_game   735 non-null    float64\n",
      " 24  drb_per_game   735 non-null    float64\n",
      " 25  trb_per_game   735 non-null    float64\n",
      " 26  ast_per_game   735 non-null    float64\n",
      " 27  stl_per_game   735 non-null    float64\n",
      " 28  blk_per_game   735 non-null    float64\n",
      " 29  tov_per_game   735 non-null    float64\n",
      " 30  pf_per_game    735 non-null    float64\n",
      " 31  pts_per_game   735 non-null    float64\n",
      "dtypes: float64(25), int64(2), object(5)\n",
      "memory usage: 189.5+ KB\n"
     ]
    }
   ],
   "source": [
    "per_game_25 = per_game[per_game['season'] == 2025]\n",
    "\n",
    "per_game_25.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "316451c2-66b8-48ab-bcb8-02e8526bd68d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>player</th>\n",
       "      <th>pts_per_game</th>\n",
       "      <th>trb_per_game</th>\n",
       "      <th>ast_per_game</th>\n",
       "      <th>fg_percent</th>\n",
       "      <th>x3p_percent</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>player_id</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>achiupr01</th>\n",
       "      <td>Precious Achiuwa</td>\n",
       "      <td>6.6</td>\n",
       "      <td>5.6</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.502</td>\n",
       "      <td>0.278</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>adamsst01</th>\n",
       "      <td>Steven Adams</td>\n",
       "      <td>3.9</td>\n",
       "      <td>5.6</td>\n",
       "      <td>1.1</td>\n",
       "      <td>0.545</td>\n",
       "      <td>0.000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>adebaba01</th>\n",
       "      <td>Bam Adebayo</td>\n",
       "      <td>18.1</td>\n",
       "      <td>9.6</td>\n",
       "      <td>4.3</td>\n",
       "      <td>0.485</td>\n",
       "      <td>0.357</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>agbajoc01</th>\n",
       "      <td>Ochai Agbaji</td>\n",
       "      <td>10.4</td>\n",
       "      <td>3.8</td>\n",
       "      <td>1.5</td>\n",
       "      <td>0.498</td>\n",
       "      <td>0.399</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>aldamsa01</th>\n",
       "      <td>Santi Aldama</td>\n",
       "      <td>12.5</td>\n",
       "      <td>6.4</td>\n",
       "      <td>2.9</td>\n",
       "      <td>0.483</td>\n",
       "      <td>0.368</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                     player  pts_per_game  trb_per_game  ast_per_game  \\\n",
       "player_id                                                               \n",
       "achiupr01  Precious Achiuwa           6.6           5.6           1.0   \n",
       "adamsst01      Steven Adams           3.9           5.6           1.1   \n",
       "adebaba01       Bam Adebayo          18.1           9.6           4.3   \n",
       "agbajoc01      Ochai Agbaji          10.4           3.8           1.5   \n",
       "aldamsa01      Santi Aldama          12.5           6.4           2.9   \n",
       "\n",
       "           fg_percent  x3p_percent  \n",
       "player_id                           \n",
       "achiupr01       0.502        0.278  \n",
       "adamsst01       0.545        0.000  \n",
       "adebaba01       0.485        0.357  \n",
       "agbajoc01       0.498        0.399  \n",
       "aldamsa01       0.483        0.368  "
      ]
     },
     "execution_count": 33,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "per_game_25_agg = per_game_25.groupby('player_id').agg({\n",
    "    'player': 'first',\n",
    "    'pts_per_game': 'mean',\n",
    "    'trb_per_game': 'mean',\n",
    "    'ast_per_game': 'mean',\n",
    "    'fg_percent': 'mean',\n",
    "    'x3p_percent': 'mean'\n",
    "})\n",
    "\n",
    "per_game_25_agg.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "d7224e09-0749-475f-969c-0eb7496cfd24",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "569"
      ]
     },
     "execution_count": 41,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "per_game_25_agg['player'].nunique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "24386f31-dc43-4958-a54d-369082ab5272",
   "metadata": {},
   "outputs": [],
   "source": [
    "scaler = StandardScaler()\n",
    "\n",
    "X_scaled = scaler.fit_transform(per_game_25_agg[['pts_per_game', 'trb_per_game', 'ast_per_game', 'fg_percent', 'x3p_percent']])\n",
    "\n",
    "st.title('Player Similarity Tool')\n",
    "\n",
    "selected_player = st.selectbox('Select a player', per_game_25_agg['player'])\n",
    "\n",
    "idx = per_game_25_agg[per_game_25_agg['player'] == selected_player].index[0]\n",
    "\n",
    "similarities = cosine_similarity([X_scaled[idx]], X_scaled)[0]\n",
    "\n",
    "per_game_25_agg['Similarity'] = similarities\n",
    "\n",
    "top_similar = per_game_25_agg[per_game_25_agg['player'] != selected_player].sort_values(by = 'Similarity', ascending = False).head()\n",
    "\n",
    "st.subheader(f'Players most similar to {selected_player}')\n",
    "st.dataframe(top_similar[['player', 'Similarity']])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
